### ISSUE TITLE
customization options improvement

### ISSUE THREAD

**Issue by brocorp-dev** [frappe/charts#284]
#### Expected Behaviour
![image](https://user-images.githubusercontent.com/46473786/81404421-7848da00-9146-11ea-8212-628fa900588c.png)

#### Actual Behaviour
![image](https://user-images.githubusercontent.com/46473786/81404451-8c8cd700-9146-11ea-9040-9bdc5b1567f5.png)

#### customization improvements:

Hi guys, 

I discovered Frappe Charts few days ago and it seems a serious alternative to another charts librairies like D3.js, Apexcharts, ChartJS, etc...  

However, due to fewer customization options, it's not possible actually to create a sparkline-like charts with Frappe Charts. 

Do you think if we'll can in a near future create charts like in 'Expected Behaviour", with 
- no extra-padding, 
- no labels for X and Y axis
- a way to provide more options for annotations, like line color and more stylable text (background, font-size, color, padding, margin)?  

Thanks for your work, your team rocks!

Frappé Charts version: 1.3.2

**Comment by scmmishra** [comment]
> it's not possible actually to create a sparkline-like charts with Frappe Charts.

Hey, I am working towards version 2 for frappe charts. It'll be more customizable. And sure you can have more cleaner charts with lesser elements

**Comment by jesper-bylund** [comment]
any news on this @scmmishra ? I'd love to be able to customise padding.

**Comment by quiquelhappy** [comment]
is this implemented now? I really want to add [Sparklines](https://vuetifyjs.com/en/components/sparklines/)

**Comment by quiquelhappy** [comment]
I got decent results with
```css
.chart-legend,
.line-vertical,
text,
.graph-svg-tip.comparison,
.y.axis {
    width: 0px;
    height: 0px;
    visibility: hidden;
}

.chart-container{
    transform: scale(1.18) translateX(-1.2%);
}
```

but I'd love to see this available as a setting
